### ISSUE TITLE
pubsub: Support the PUBSUB_HOST environment variable

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/gcloud-ruby#589] opened 2016-03-18 19:37 UTC
Other GCP client libraries support the PUBSUB_HOST environment variable for overriding the address of the pubsub instance to connect to, which is particularly useful for connecting to a local instance of the pubsub emulator for testing.

See here for how the node library handles this:
https://github.com/GoogleCloudPlatform/gcloud-node/blob/36a9f5c931a8d5f6fa566205cccae71ba99b79d5/lib/pubsub/index.js#L86

**Comment by blowmage** [comment] 2016-03-18 20:31
Agreed, this will be useful. 

Duplicate of #491.

**Comment by dlorenc** [comment] 2016-03-21 20:56
Thanks! Any idea when you can get to this? I'm happy to help if that would speed things up :)

**Comment by quartzmo** [comment] 2016-03-28 15:35
@blowmage Should this be part of 0.7.0 - Logging milestone? Also, should we close one of these issues as duplicate?

**Comment by blowmage** [comment] 2016-03-28 15:53
Yes, this should be in scope of the next release milestone. I'm okay keeping both issues open as long as the issue has not been resolved. But I'm also not opposed to closing this one as a duplicate of the older issue. What do you think?

**Comment by quartzmo** [comment] 2016-03-28 17:22
Agreed. Closing as duplicate of #491 

@dlorenc I'm going to start work on this now. We hope to have it released within the week.

**Closed by quartzmo** 2016-03-28 17:22 UTC
Labels: pubsub
